#data
Variable_Data_Fields={
    '--Control Information, Number, and Codes - General Information--':"--",
    '010: Library of Congress Control Number':"010 ##",
    '013: Patent Control Information':"013 ##",
    '015: National Bibliography Number':"015 ##",
    '016: National Bibliography Agency Control Number':"016 ##",
    '017: Copyright or Legal Deposit Number':"017 ##",
    '018: Copyright Article-Fee Code':"018 ##",
    '020: International Standard Book Number (ISBN)':"020 ##",
    '022: International Standard Serial Number (ISSN)':"022 ##",
    '024: Other Standard Identifier':"024 ##",
    '025: Overseas Acquisition Number':"025 ##",
    '027: Standard Technincal Report Number':"027 ##",
    '028: Publisher or Distributer Number':"028 ##",
    '030: CODEN Designation':"030 ##",
    '031: Musical Incipits Information':"031 ##",
    '032: Postal Registration Number':"032 ##",
    '033: Date/Time and Place of an Event':"033 ##",
    '034: Coded Cartographic Mathematical Data':"034 ##",
    '035: System Control Number':"035 ##",
    '036: Original Study Number for Computer Data files':"036 ##",
    '037: Source of Acquisition':"037 ##",
    '038: Record Content Licensor':"038 ##",
    '040: Cataloging Source':"040 ##",
    '041: Language Code':"041 ##",
    '042: Authentication Code':"042 ##",
    '043: Geographic Area Code':"043 ##",
    '044: Country of Publishing/Producing Entity Code':"044 ##",
    '045: Time Period of Content':"045 ##",
    '046: Special Coded Dates':"046 ##",
    '047: Form of Musical Composition Code':"047 ##",
    '048: Number of Musical Instruments or Voices Code':"048 ##",
    '050: Library of Congress Call Number':"050 ##",
    '051: Library of Congress Copy, Issue, Offprint Statement':"051 ##",
    '052: Geographic Classification':"052 ##",
    '055: Classification Numbers Assigned in Canada':"055 ##",
    '060: National Library of Medicine Call Number':"060 ##",
    '061: National Library of Medicine Copy Statement':"061 ##",
    '066: Character Sets Present':"066 ##",
    '070: National Agricultural Library Call Number':"070 ##",
    '071: National Agricultural Library Copy Statement':"071 ##",
    '072: Subject Category Code':"072 ##",
    '074: GPO Item Number':"074 ##",
    '080: Universal Decimal Classification Number':"080 ##",
    '082: Dewey Decimal Classification Number':"082 ##",
    '083: Additional Dewey Decimal Classification Number':"083 ##",
    '084: Other Classification Number':"084 ##",
    '085: Synthesized Classification Number Components':"085 ##",
    '086: Government Document Classification Number':"086 ##",
    '088: Report Number':"088 ##",
    '--Title and Title-Related Fields - General Information--':"--",
    '210: Abbreviated Title':"210 ##",
    '222: Key Title':"222 ##",
    '240: Uniform Title':"240 ##",
    '242: Translation of Title by Cataloging Agency':"242 ##",
    '243: Collective Uniform Title':"243 ##",
    '245: Title Statement':"245 ##",
    '246: Varying Form of Title':"246 ##",
    '247: Former Title':"247 ##",
    }



subfield={
    '--':{
    '--':"",
    },
    '010 ##':{
    'LC control number':"$a",
    'NUCMC control number':"$b",
    'Canceled/invalid LC control number':"$z",
    'Field link and sequence number':"$8",
    },
    '013 ##':{
    'Number':"$a",
    'Country':"$b",
    'Type of number':"$c",
    'Date':"$d",
    'Status':"$e",
    'Party of document':"$f",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '015 ##':{
    'National bibliography number':"$a",
    'Qualifying information':"$q",
    'Canceled/invalid national bibliography number':"$z",
    'Source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '016 ##':{
    'Record control number':"$a",
    'Canceled/invalid control number':"$z",
    'Source':"$2",
    'Field link and sequence number':"$8",
    },
    '017 ##':{
    'Copyright or legal deposit number':"$a",
    'Assigning agency':"$b",
    'Date':"$d",
    'Display text':"$i",
    'Canceled/invalid copyright or legal deposit number':"$z",
    'Source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '018 ##':{
    'Copyright article-fee code':"$a",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '020 ##':{
    'International Standard Book Number':"$a",
    'Terms of availability':"$c",
    'Qualifying information':"$q",
    'Canceled/invalid ISBN':"$z",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '022 ##':{
    'International Standard Serial Number':"$a",
    'ISSN-L':"$l",
    'Canceled ISSN-L':"$m",
    'Incorrect ISSN':"$y",
    'Canceled ISSN':"$z",
    'Source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '024 ##':{
    'Standard number or code':"$a",
    'Terms of availability':"$c",
    'Additional codes following the standard number or code':"$d",
    'Qualifying information':"$q",
    'Canceled/invalid standard number or code':"$z",
    'Source of number or code':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '025 ##':{
    'Overseas acquisition number':"$a",
    'Field link and sequence number':"$8",
    },
    '027 ##':{
    'Standard technical report number':"$a",
    'Qualifying information':"$q",
    'Canceled/invalid number':"$z",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '028 ##':{
    'Publisher or distributor number':"$a",
    'Source':"$b",
    'Qualifying information':"$q",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '030 ##':{
    'CODEN':"$a",
    'Canceled/invalid number':"$z",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
     '031 ##':{
    'Number of work':"$a",
    'Number of movement':"$b",
    'Number of excerpt':"$c",
    'Caption or heading':"$d",
    'Role':"$e",
    'Clef':"$g",
    'Voice/instrument':"$m",
    'Key signature':"$n",
    'Time signature':"$o",
    'Musical notation':"$p",
    'General note':"$q",
    'Key or mode':"$r",
    'Coded validity note':"$s",
    'Text incipit':"$t",
    'Uniform Resource Identifier':"$u",
    'Link text':"$y",
    'Public note':"$z",
    'System code':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '032 ##':{
    'Postal registration number':"$a",
    'Source agency assigning number':"$b",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '033 ##':{
    'Formatted date/time':"$a",
    'Geographic classification area code':"$b",
    'Geographic classification subarea code':"$c",
    'Place of event':"$p",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of term':"$2",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '034 ##':{
    'Catagory of scale':"$a",
    'Constant ratio linear horizontal scale':"$b",
    'Constant ratio linear vertical scale':"$c",
    'Coordinates - westernmost longitude':"$d",
    'Coordinates - easternmost longitude':"$e",
    'Coordinates - northernmost latitude':"$f",
    'Coordinates - southernmost latitude':"$g",
    'Angular scale':"$h",
    'Declination - northern limit':"$j",
    'Declination - southern limit':"$k",
    'Right ascention - eastern limit':"$m",
    'Right ascention - western limit':"$n",
    'Equinox':"$p",
    'Distance from earth':"$r",
    'G-ring latitude':"$s",
    'G-ring longitude':"$t",
    'Beginning date':"$x",
    'Ending date':"$y",
    'Name of extraterrestrial body':"$z",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of term':"$2",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '035 ##':{
    'System control number':"$a",
    'Canceled/invalid control number':"$z",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '036 ##':{
    'Original study number':"$a",
    'Source agency assigning number':"$b",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '037 ##':{
    'Stock number':"$a",
    'Source of stock number/acquisition':"$b",
    'Terms of availability':"$c",
    'Form of issue':"$f",
    'Additional format characteristics':"$g",
    'Note':"$n",
    'Materials specified':"$3",
    'Institution to which field applies':"$5",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '038 ##':{
    'Record content licensor':"$a",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '040 ##':{
    'Origional cataloging agency':"$a",
    'Language of cataloging':"$b",
    'Transcribing agency':"$c",
    'Modifying agency':"$d",
    'Description conventions':"$e",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '041 ##':{
    'Language code of text/sound track or separate title':"$a",
    'Language code of summary or abstract':"$b",
    'Language code of sung or spoken text':"$d",
    'Language code of librettos':"$e",
    'Language code of table of contents':"$f",
    'Language code of accompanying material other than librettos':"$g",
    'Language code of original':"$h",
    'Language code of subtitles or captions':"$j",
    'Language code of intermediate translations':"$k",
    'Language code of original accompanying materials other than librettos':"$m",
    'Language code of original libretto':"$n",
    'Source of term':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '042 ##':{
    'Authentication code':"$a",
    },
    '043 ##':{
    'Geographic area code':"$a",
    'Local GAC code':"$b",
    'ISO code':"$c",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of term':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '044 ##':{
    'MARC country code':"$a",
    'Local subentity code':"$b",
    'ISO country code':"$c",
    'Source of term':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '045 ##':{
    'Time period code':"$a",
    'Formatted 9999 B.C. through C.E. time period':"$b",
    'Formated pre-9999 B.C. time period':"$c",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '046 ##':{
    'Type of date code':"$a",
    'Date 1, B.C.E. date':"$b",
    'Date 1, C.E. date':"$c",
    'Date 2, B.C.E. date':"$d",
    'Date 2, C.E. date':"$e",
    'Date resource modified':"$j",
    'Beginning or single date created':"$k",
    'Ending date created':"$l",
    'Beginning of date valid':"$m",
    'End of date valid':"$n",
    'Single or starting date for aggregated content':"$o",
    'Ending date for aggregated content':"$p",
    'Source of term':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '047 ##':{
    'Form of musical composition code':"$a",
    'Source of code':"$2",
    'Field link and sequence number':"$8",
    },
    '048 ##':{
    'Performer or ensemble':"$a",
    'Soloist':"$b",
    'Source of code':"$2",
    'Field link and sequence number':"$8",
    },
    '050 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '051 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Copy information':"$c",
    'Field link and sequence number':"$8",
    },
    '052 ##':{
    'Geographic classification area code':"$a",
    'Geographic classification subarea code':"$b",
    'Populated place name':"$d",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Code source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '055 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of call/class number':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '060 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Field link and sequence number':"$8",
    },
    '061 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Copy information':"$c",
    'Field link and sequence number':"$8",
    },
    '066 ##':{
    'Primary G0 character set':"$a",
    'Primary G1 character set':"$b",
    'Alternate G0 or G1 character set':"$c",
    },
    '070 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Field link and sequence number':"$8",
    },
    '071 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Copy information':"$c",
    'Field link and sequence number':"$8",
    },
    '072 ##':{
    'Subject category code':"$a",
    'Subject category code subdivision':"$x",
    'Source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '074 ##':{
    'GPO item number':"$a",
    'Canceled/invalid GPO item number':"$z",
    'Field link and sequence number':"$8",
    },
    '080 ##':{
    'Universal Decimal Classification number':"$a",
    'Item number':"$b",
    'Common auxiliary subdivision':"$x",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Edition identifier':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '082 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Standard or optional designation':"$m",
    'Assigning agency':"$q",
    'Edition number':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '083 ##':{
    'Classification number':"$a",
    'Classification number--Ending number of span':"$c",
    'Standard or optional designation':"$m",
    'Assigning agency':"$q",
    'Table sequence number for internal subarrangement or add table':"$y",
    'Table identification':"$z",
    'Edition number':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '084 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Assigning agency':"$q",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Number source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '085 ##':{
    'Number where instructions are found-single number or beginning number of span':"$a",
    'Base number':"$b",
    'Classification number-ending number of span':"$c",
    'Facet designator':"$f",
    'Root number':"$r",
    'Digits added from classification number in schedule or external table':"$s",
    'Digits added from internal subarrangement or add table':"$t",
    'number being analyzed':"$u",
    'Number in internal subarrangement or add table where instructions are found':"$v",
    'Table identification-Internal subarrangement or add table':"$w",
    'Table sequence number for internal subarrangement or add table':"$y",
    'Table identification':"$z",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '086 ##':{
    'Classification number':"$a",
    'Canceled/invalid classification number':"$z",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Number source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '088 ##':{
    'Report number':"$a",
    'Canceled/invalid report number':"$z",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '210 ##':{
    'Abbreviated title':"$a",
    'Qualifying information':"$b",
    'Source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '222 ##':{
    'Key title':"$a",
    'Qualifying information':"$b",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '240 ##':{
    'Uniform title':"$a",
    'Date of treaty signing':"$d",
    'Date of a work':"$f",
    'Miscellaneous information':"$g",
    'Medium':"$h",
    'Form subheading':"$k",
    'Language of a work':"$l",
    'Medium of performance for music':"$m",
    'Number of part/section of a work':"$n",
    'Arranged statement for music':"$o",
    'Name of part/section of a work':"$p",
    'Key for music':"$r",
    'Version':"$s",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '242 ##':{
    'Title':"$a",
    'Remainder of title':"$b",
    'Statement of responsibility, etc.':"$c",
    'Medium':"$h",
    'Number of part/section of a work':"$n",
    'Name of part/section of a work':"$p",
    'Language code of translated title':"$y",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '243 ##':{
    'Uniform title':"$a",
    'Date of treaty signing':"$d",
    'Date of a work':"$f",
    'Miscellaneous information':"$g",
    'Medium':"$h",
    'Form subheading':"$k",
    'Language of a work':"$l",
    'Medium of performance for music':"$m",
    'Number of part/section of a work':"$n",
    'Arranged statement for music':"$o",
    'Name of part/section of a work':"$p",
    'Key for music':"$r",
    'Version':"$s",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '245 ##':{
    'Title':"$a",
    'Remainder of title':"$b",
    'Statement of responsibility, etc.':"$c",
    'Inclusive dates':"$f",
    'Bulk dates':"$g",
    'Medium':"$h",
    'Form':"$k",
    'Number of part/section of a work':"$n",
    'Name of part/section of a work':"$p",
    'Version':"$s",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '246 ##':{
    'Title proper/short title':"$a",
    'Remainder of title':"$b",
    'Date or sequential designation':"$f",
    'Miscellaneous information':"$g",
    'Medium':"$h",
    'Display text':"$i",
    'Number of part/section of a work':"$n",
    'Name of part/section of a work':"$p",
    'Institution to which field applies':"$5",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '247 ##':{
    'Title':"$a",
    'Remainder of title':"$b",
    'Date or sequential designation':"$f",
    'Miscellaneous information':"$g",
    'Medium':"$h",
    'Number of part/section of a work':"$n",
    'Name of part/section of a work':"$p",
    'International Standard Serial Number':"$x",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    }

Indicator={
    '010 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '013 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '015 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '016 ##':"-----First Indicator-----\nnational bibliographic agency\n# - Library and Archives Canada\n7 - Source specified in subfield $2\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '017 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\ndisplay constant controller\n# - Copyright/legal deposit number\n8 - No display constant generated"
    ,
    '018 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '020 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '022 ##':"-----First Indicator-----\nlevel of international interest\n# - No level specified\n0 - Continuing international interest\n1 - No continuing international interest\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '024 ##':"-----First Indicator-----\ntype of standard number or code\n0 - International Standard Recording Code\n1 - Universal Product Code\n2 - International Standard Music Number\n3 - International Article Number\n4 - Serial Item/Contribution Identifier\n7 - Source specified in subfield $2\n8 - Unspecified type of standard number/code\n-----Second Indicator-----\ndifference indicator\n# - No information provided\n0 - No difference\n1 - Difference"
    ,
    '025 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '027 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '028 ##':"-----First Indicator-----\ntype of number\n0 - Issue number\n1 - Matrix number\n2 - Plate number\n3 - Other music publisher number\n4 - Video recording publisher number\n5 - Other publisher number\n6 - Distributor number\n-----Second Indicator-----\nnote/added entry controller\n0 - No note, no added entry\n1 - Note, added entry\n2 - Note, no added entry\n3 - No note, added entry"
    ,
    '030 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '031 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '032 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '033 ##':"-----First Indicator-----\ntype of date in subfield $a\n# - No date information\n0 - Single date\n1 - Multiple single dates\n2 - Range of dates\n-----Second Indicator-----\ntype of event\n# - No information provided\n0 - Capture\n1 - Broadcast\n2 - Finding"
    ,
    '034 ##':"-----First Indicator-----\ntype of scale\n0 - Scale indeterminable/No scale recorded\n1 - Single scale\n3 - Range of scales\n-----Second Indicator-----\ntype of ring\n# - Not applicable\n0 - Outer ring\n1 - Exclusion ring"
    ,
    '035 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '036 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '037 ##':"-----First Indicator-----\nsource of acquisition sequence\n# - Not applicable/No information provided/Earliest\n2 - Intervening\n3 - Current/Latest\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '038 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '040 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '041 ##':"-----First Indicator-----\ntranslation indication\n# - No information provided\n0 - Item not a translation/does not include a translation\n1 - Item is or includes a translation\n-----Second Indicator-----\nsource of code\n# - MARC language code\n7 - Source specified in subfield $2"
    ,
    '042 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '043 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '044 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '045 ##':"-----First Indicator-----\ntype of time period in subfield $b or $c\n# - Subfield $b or $c not present\n0 - Single date/time\n1 - Multiple single dates/times\n2 - Range of dates/times\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '046 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    '047 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nsource of code\n# - MARC musical composition code\n7 - Source specified in subfield $2"
    ,
    '048 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nsource of code\n# - MARC code\n7 - Source specified in subfield $2"
    ,
    '050 ##':"-----First Indicator-----\nexistence in LC collection\n# - No information provided\n0 - Item is in LC\n1 - Item is not in LC\n-----Second Indicator-----\nsource of call number\n0 - Assigned by LC\n4 - Assigned by agency other than LC"
    ,
    '051 ##':"-----First Indicator-----\nundefined\n# - Undefined\n-----Second Indicator-----\nundefined\n# - Undefined"
    ,
    }

