#data
Variable_Data_Fields={
    '-----Control Information, Number, and Codes-----':"--",
    '010: Library of Congress Control Number':"010 ##",
    '013: Patent Control Information':"013 ##",
    '015: National Bibliography Number':"015 ##",
    '016: National Bibliography Agency Control Number':"016 ##",
    '017: Copyright or Legal Deposit Number':"017 ##",
    '018: Copyright Article-Fee Code':"018 ##",
    '020: International Standard Book Number (ISBN)':"020 ##",
    '022: International Standard Serial Number (ISSN)':"022 ##",
    '024: Other Standard Identifier':"024 ##",
    '025: Overseas Acquisition Number':"025 ##",
    '027: Standard Technincal Report Number':"027 ##",
    '028: Publisher or Distributer Number':"028 ##",
    '030: CODEN Designation':"030 ##",
    '031: Musical Incipits Information':"031 ##",
    '032: Postal Registration Number':"032 ##",
    '033: Date/Time and Place of an Event':"033 ##",
    '034: Coded Cartographic Mathematical Data':"034 ##",
    '035: System Control Number':"035 ##",
    '036: Original Study Number for Computer Data files':"036 ##",
    '037: Source of Acquisition':"037 ##",
    '038: Record Content Licensor':"038 ##",
    '040: Cataloging Source':"040 ##",
    '041: Language Code':"041 ##",
    '042: Authentication Code':"042 ##",
    '043: Geographic Area Code':"043 ##",
    '044: Country of Publishing/Producing Entity Code':"044 ##",
    '045: Time Period of Content':"045 ##",
    '046: Special Coded Dates':"046 ##",
    '047: Form of Musical Composition Code':"047 ##",
    '048: Number of Musical Instruments or Voices Code':"048 ##",
    '050: Library of Congress Call Number':"050 ##",
    '051: Library of Congress Copy, Issue, Offprint Statement':"051 ##",
    '052: Geographic Classification':"052 ##",
    '055: Classification Numbers Assigned in Canada':"055 ##",
    '060: National Library of Medicine Call Number':"060 ##",
    '061: National Library of Medicine Copy Statement':"061 ##",
    '066: Character Sets Present':"066 ##",
    '070: National Agricultural Library Call Number':"070 ##",
    '071: National Agricultural Library Copy Statement':"071 ##",
    '072: Subject Category Code':"072 ##",
    '074: GPO Item Number':"074 ##",
    '080: Universal Decimal Classification Number':"080 ##",
    '082: Dewey Decimal Classification Number':"082 ##",
    '083: Additional Dewey Decimal Classification Number':"083 ##",
    '084: Other Classification Number':"084 ##",
    '085: Synthesized Classification Number Components':"085 ##",
    '086: Government Document Classification Number':"086 ##",
    '088: Report Number':"088 ##",
    '-----Title and Title-Related Fields-----':"--",
    '210: Abbreviated Title':"210 ##",
    '222: Key Title':"222 ##",
    '240: Uniform Title':"240 ##",
    '242: Translation of Title by Cataloging Agency':"242 ##",
    '243: Collective Uniform Title':"243 ##",
    '245: Title Statement':"245 ##",
    '246: Varying Form of Title':"246 ##",
    '247: Former Title':"247 ##",
    '-----Edition, Imprint, Etc. Fields-----':"--",
    '250: Edition Statement':"250 ##",
    '254: Musical Presentation Statement':"254 ##",
    '255: Cartographic Mathematical Data':"255 ##",
    '256: Computer File Characteristics':"256 ##",
    '257: Country of Producing Entity':"257 ##",
    '258: Philatelic Issue Data':"258 ##",
    '260: Publication, Distribution, etc. (Imprint)':"260 ##",
    '263: Projected Publication Date':"263 ##",
    '264: Production, Publication, Distribution, Manufacture, and Copyright Notice':"264 ##",
    '270: Address':"270 ##",
    '-----Physical Description, Etc. Fields-----':"--",
    '300: Physical Description':"300 ##",
    '306: Playing Time':"306 ##",
    '307: Hours, Etc.':"307 ##",
    '310: Current Publication Frequency':"310 ##",
    '321: Former Publication Frequency':"321 ##",
    '336: Content Type':"336 ##",
    '337: Media Type':"337 ##",
    '338: Carrier Type':"338 ##",
    '340: Physical Medium':"340 ##",
    '342: Geospacial Reference Data':"342 ##",
    '343: Planar Coordinate Data':"343 ##",
    '344: Sound Characteristics':"344 ##",
    '345: Projection Characteristics of Moving Image':"345 ##",
    '346: Video Characteristics':"346 ##",
    '347: Digital File Characteristics':"347 ##",
    '348: Format of Notated Music':"348 ##",
    '351: Organization and Arrangement of Materials':"351 ##",
    '352: Digitl Graphic Representation':"352 ##",
    '355: Security Classification Control':"355 ##",
    '357: Originator Dissemination Control':"357 ##",
    '362: Dates of Publication and/or Sequential Designation':"362 ##",
    '363: Normalized Date and Sequential Designation':"363 ##",
    '365: Trade Price':"365 ##",
    '366: Trade Availability Information':"366 ##",
    '370: Associated Place':"370 ##",
    '377: Associated Language':"377 ##",
    '380: Form of Work':"380 ##",
    '381: Other Distinguishing Characteristics of Work or Expression':"381 ##",
    '382: Medium of Performance':"382 ##",
    '383: Numeric Designation of Musical Work':"383 ##",
    '384: Key':"384 ##",
    '385: Audience Characteristics':"385 ##",
    '386: Creator/Contributor Characteristics':"386 ##",
    '388: Time Period of Creation':"388 ##",
    '-----Series Statements-----':"--",
    '490: Series Statement':"490 ##",
    '-----Notes-----':"--",
    '500: General Note':"500 ##",
    '501: With Note':"501 ##",
    '502: Dissertation Note':"502 ##",
    '504: Bibliography, Etc. Note':"504 ##",
    '505: Formatted Contents Note':"505 ##",
    }



subfield={
    '--':{
    '--':"",
    },
    '010 ##':{
    'LC control number':"$a",
    'NUCMC control number':"$b",
    'Canceled/invalid LC control number':"$z",
    'Field link and sequence number':"$8",
    },
    '013 ##':{
    'Number':"$a",
    'Country':"$b",
    'Type of number':"$c",
    'Date':"$d",
    'Status':"$e",
    'Party of document':"$f",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '015 ##':{
    'National bibliography number':"$a",
    'Qualifying information':"$q",
    'Canceled/invalid national bibliography number':"$z",
    'Source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '016 ##':{
    'Record control number':"$a",
    'Canceled/invalid control number':"$z",
    'Source':"$2",
    'Field link and sequence number':"$8",
    },
    '017 ##':{
    'Copyright or legal deposit number':"$a",
    'Assigning agency':"$b",
    'Date':"$d",
    'Display text':"$i",
    'Canceled/invalid copyright or legal deposit number':"$z",
    'Source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '018 ##':{
    'Copyright article-fee code':"$a",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '020 ##':{
    'International Standard Book Number':"$a",
    'Terms of availability':"$c",
    'Qualifying information':"$q",
    'Canceled/invalid ISBN':"$z",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '022 ##':{
    'International Standard Serial Number':"$a",
    'ISSN-L':"$l",
    'Canceled ISSN-L':"$m",
    'Incorrect ISSN':"$y",
    'Canceled ISSN':"$z",
    'Source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '024 ##':{
    'Standard number or code':"$a",
    'Terms of availability':"$c",
    'Additional codes following the standard number or code':"$d",
    'Qualifying information':"$q",
    'Canceled/invalid standard number or code':"$z",
    'Source of number or code':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '025 ##':{
    'Overseas acquisition number':"$a",
    'Field link and sequence number':"$8",
    },
    '027 ##':{
    'Standard technical report number':"$a",
    'Qualifying information':"$q",
    'Canceled/invalid number':"$z",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '028 ##':{
    'Publisher or distributor number':"$a",
    'Source':"$b",
    'Qualifying information':"$q",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '030 ##':{
    'CODEN':"$a",
    'Canceled/invalid number':"$z",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
     '031 ##':{
    'Number of work':"$a",
    'Number of movement':"$b",
    'Number of excerpt':"$c",
    'Caption or heading':"$d",
    'Role':"$e",
    'Clef':"$g",
    'Voice/instrument':"$m",
    'Key signature':"$n",
    'Time signature':"$o",
    'Musical notation':"$p",
    'General note':"$q",
    'Key or mode':"$r",
    'Coded validity note':"$s",
    'Text incipit':"$t",
    'Uniform Resource Identifier':"$u",
    'Link text':"$y",
    'Public note':"$z",
    'System code':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '032 ##':{
    'Postal registration number':"$a",
    'Source agency assigning number':"$b",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '033 ##':{
    'Formatted date/time':"$a",
    'Geographic classification area code':"$b",
    'Geographic classification subarea code':"$c",
    'Place of event':"$p",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of term':"$2",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '034 ##':{
    'Catagory of scale':"$a",
    'Constant ratio linear horizontal scale':"$b",
    'Constant ratio linear vertical scale':"$c",
    'Coordinates - westernmost longitude':"$d",
    'Coordinates - easternmost longitude':"$e",
    'Coordinates - northernmost latitude':"$f",
    'Coordinates - southernmost latitude':"$g",
    'Angular scale':"$h",
    'Declination - northern limit':"$j",
    'Declination - southern limit':"$k",
    'Right ascention - eastern limit':"$m",
    'Right ascention - western limit':"$n",
    'Equinox':"$p",
    'Distance from earth':"$r",
    'G-ring latitude':"$s",
    'G-ring longitude':"$t",
    'Beginning date':"$x",
    'Ending date':"$y",
    'Name of extraterrestrial body':"$z",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of term':"$2",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '035 ##':{
    'System control number':"$a",
    'Canceled/invalid control number':"$z",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '036 ##':{
    'Original study number':"$a",
    'Source agency assigning number':"$b",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '037 ##':{
    'Stock number':"$a",
    'Source of stock number/acquisition':"$b",
    'Terms of availability':"$c",
    'Form of issue':"$f",
    'Additional format characteristics':"$g",
    'Note':"$n",
    'Materials specified':"$3",
    'Institution to which field applies':"$5",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '038 ##':{
    'Record content licensor':"$a",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '040 ##':{
    'Origional cataloging agency':"$a",
    'Language of cataloging':"$b",
    'Transcribing agency':"$c",
    'Modifying agency':"$d",
    'Description conventions':"$e",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '041 ##':{
    'Language code of text/sound track or separate title':"$a",
    'Language code of summary or abstract':"$b",
    'Language code of sung or spoken text':"$d",
    'Language code of librettos':"$e",
    'Language code of table of contents':"$f",
    'Language code of accompanying material other than librettos':"$g",
    'Language code of original':"$h",
    'Language code of subtitles or captions':"$j",
    'Language code of intermediate translations':"$k",
    'Language code of original accompanying materials other than librettos':"$m",
    'Language code of original libretto':"$n",
    'Source of term':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '042 ##':{
    'Authentication code':"$a",
    },
    '043 ##':{
    'Geographic area code':"$a",
    'Local GAC code':"$b",
    'ISO code':"$c",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of term':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '044 ##':{
    'MARC country code':"$a",
    'Local subentity code':"$b",
    'ISO country code':"$c",
    'Source of term':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '045 ##':{
    'Time period code':"$a",
    'Formatted 9999 B.C. through C.E. time period':"$b",
    'Formated pre-9999 B.C. time period':"$c",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '046 ##':{
    'Type of date code':"$a",
    'Date 1, B.C.E. date':"$b",
    'Date 1, C.E. date':"$c",
    'Date 2, B.C.E. date':"$d",
    'Date 2, C.E. date':"$e",
    'Date resource modified':"$j",
    'Beginning or single date created':"$k",
    'Ending date created':"$l",
    'Beginning of date valid':"$m",
    'End of date valid':"$n",
    'Single or starting date for aggregated content':"$o",
    'Ending date for aggregated content':"$p",
    'Source of term':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '047 ##':{
    'Form of musical composition code':"$a",
    'Source of code':"$2",
    'Field link and sequence number':"$8",
    },
    '048 ##':{
    'Performer or ensemble':"$a",
    'Soloist':"$b",
    'Source of code':"$2",
    'Field link and sequence number':"$8",
    },
    '050 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '051 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Copy information':"$c",
    'Field link and sequence number':"$8",
    },
    '052 ##':{
    'Geographic classification area code':"$a",
    'Geographic classification subarea code':"$b",
    'Populated place name':"$d",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Code source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '055 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of call/class number':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '060 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Field link and sequence number':"$8",
    },
    '061 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Copy information':"$c",
    'Field link and sequence number':"$8",
    },
    '066 ##':{
    'Primary G0 character set':"$a",
    'Primary G1 character set':"$b",
    'Alternate G0 or G1 character set':"$c",
    },
    '070 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Field link and sequence number':"$8",
    },
    '071 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Copy information':"$c",
    'Field link and sequence number':"$8",
    },
    '072 ##':{
    'Subject category code':"$a",
    'Subject category code subdivision':"$x",
    'Source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '074 ##':{
    'GPO item number':"$a",
    'Canceled/invalid GPO item number':"$z",
    'Field link and sequence number':"$8",
    },
    '080 ##':{
    'Universal Decimal Classification number':"$a",
    'Item number':"$b",
    'Common auxiliary subdivision':"$x",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Edition identifier':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '082 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Standard or optional designation':"$m",
    'Assigning agency':"$q",
    'Edition number':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '083 ##':{
    'Classification number':"$a",
    'Classification number--Ending number of span':"$c",
    'Standard or optional designation':"$m",
    'Assigning agency':"$q",
    'Table sequence number for internal subarrangement or add table':"$y",
    'Table identification':"$z",
    'Edition number':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '084 ##':{
    'Classification number':"$a",
    'Item number':"$b",
    'Assigning agency':"$q",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Number source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '085 ##':{
    'Number where instructions are found-single number or beginning number of span':"$a",
    'Base number':"$b",
    'Classification number-ending number of span':"$c",
    'Facet designator':"$f",
    'Root number':"$r",
    'Digits added from classification number in schedule or external table':"$s",
    'Digits added from internal subarrangement or add table':"$t",
    'number being analyzed':"$u",
    'Number in internal subarrangement or add table where instructions are found':"$v",
    'Table identification-Internal subarrangement or add table':"$w",
    'Table sequence number for internal subarrangement or add table':"$y",
    'Table identification':"$z",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '086 ##':{
    'Classification number':"$a",
    'Canceled/invalid classification number':"$z",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Number source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '088 ##':{
    'Report number':"$a",
    'Canceled/invalid report number':"$z",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '210 ##':{
    'Abbreviated title':"$a",
    'Qualifying information':"$b",
    'Source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '222 ##':{
    'Key title':"$a",
    'Qualifying information':"$b",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '240 ##':{
    'Uniform title':"$a",
    'Date of treaty signing':"$d",
    'Date of a work':"$f",
    'Miscellaneous information':"$g",
    'Medium':"$h",
    'Form subheading':"$k",
    'Language of a work':"$l",
    'Medium of performance for music':"$m",
    'Number of part/section of a work':"$n",
    'Arranged statement for music':"$o",
    'Name of part/section of a work':"$p",
    'Key for music':"$r",
    'Version':"$s",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '242 ##':{
    'Title':"$a",
    'Remainder of title':"$b",
    'Statement of responsibility, etc.':"$c",
    'Medium':"$h",
    'Number of part/section of a work':"$n",
    'Name of part/section of a work':"$p",
    'Language code of translated title':"$y",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '243 ##':{
    'Uniform title':"$a",
    'Date of treaty signing':"$d",
    'Date of a work':"$f",
    'Miscellaneous information':"$g",
    'Medium':"$h",
    'Form subheading':"$k",
    'Language of a work':"$l",
    'Medium of performance for music':"$m",
    'Number of part/section of a work':"$n",
    'Arranged statement for music':"$o",
    'Name of part/section of a work':"$p",
    'Key for music':"$r",
    'Version':"$s",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '245 ##':{
    'Title':"$a",
    'Remainder of title':"$b",
    'Statement of responsibility, etc.':"$c",
    'Inclusive dates':"$f",
    'Bulk dates':"$g",
    'Medium':"$h",
    'Form':"$k",
    'Number of part/section of a work':"$n",
    'Name of part/section of a work':"$p",
    'Version':"$s",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '246 ##':{
    'Title proper/short title':"$a",
    'Remainder of title':"$b",
    'Date or sequential designation':"$f",
    'Miscellaneous information':"$g",
    'Medium':"$h",
    'Display text':"$i",
    'Number of part/section of a work':"$n",
    'Name of part/section of a work':"$p",
    'Institution to which field applies':"$5",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '247 ##':{
    'Title':"$a",
    'Remainder of title':"$b",
    'Date or sequential designation':"$f",
    'Miscellaneous information':"$g",
    'Medium':"$h",
    'Number of part/section of a work':"$n",
    'Name of part/section of a work':"$p",
    'International Standard Serial Number':"$x",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '250 ##':{
    'Edition Statement':"$a",
    'Remainder of edition statement':"$b",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '254 ##':{
    'Musical presentation statement':"$a",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '255 ##':{
    'Statement of scale':"$a",
    'Statement of projection':"$b",
    'Statement of coordinates':"$c",
    'Statement of zone':"$d",
    'Statement of equinox':"$e",
    'Outer G-ring coordinate pairs':"$f",
    'Exclusion G-ring coordinate pairs':"$q",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '256 ##':{
    'Computer file characteristics':"$a",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '257 ##':{
    'Title':"$a",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '258 ##':{
    'Issuing jurisdiction':"$a",
    'Denomination':"$b",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '260 ##':{
    'Place of publication, distribution, etc.':"$a",
    'Name of publisher, distributor, etc.':"$b",
    'Date of publication, distribution, etc.':"$c",
    'Place of manufacture':"$e",
    'Manufacturer':"$f",
    'Date of manufacture':"$g",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '263 ##':{
    'Projected publication date':"$a",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '264 ##':{
    'Place of production, publication, distribution, manufacture':"$a",
    'Name of producer, publisher, distributer, manufacturer':"$b",
    'Date of production, publication, distribution, manufacture, or copyright notice':"$c",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '270 ##':{
    'Address':"$a",
    'City':"$b",
    'State or province':"$c",
    'Country':"$d",
    'Postal code':"$e",
    'Terms preceding attention name':"$f",
    'Attention name':"$g",
    'Attention position':"$h",
    'Type of address':"$i",
    'Specialized telephone number':"$j",
    'Telephone number':"$k",
    'Fax number':"$l",
    'Electronic mail address':"$m",
    'TDD or TTY number':"$n",
    'Contact person':"$p",
    'Title of contact person':"$q",
    'Hours':"$r",
    'Public note':"$z",
    'Relationship':"$4",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '300 ##':{
    'Extent':"$a",
    'Other physical details':"$b",
    'Dimensions':"$c",
    'Accompanying material':"$e",
    'Type of unit':"$f",
    'Size of unit':"$g",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '306 ##':{
    'Playing time':"$a",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '307 ##':{
    'Hours':"$a",
    'Additional information':"$b",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '310 ##':{
    'Current publication frequency':"$a",
    'Date of current publication frequency':"$b",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '321 ##':{
    'Former publication frequency':"$a",
    'Dates of former publication frequency':"$b",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '336 ##':{
    'Content type term':"$a",
    'Content type code':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source':"$2",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '337 ##':{
    'Media type term':"$a",
    'Media type code':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source':"$2",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '338 ##':{
    'Carrier type term':"$a",
    'Carrier type code':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source':"$2",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '340 ##':{
    'Material base and configuration':"$a",
    'Dimensions':"$b",
    'Materials applied to surface':"$c",
    'Information recording technique':"$d",
    'Support':"$e",
    'Dimensions':"$f",
    'Color content':"$g",
    'Location within medium':"$h",
    'Technical specifications of medium':"$i",
    'Generation':"$j",
    'Layout':"$k",
    'Book format':"$m",
    'Font size':"$n",
    'Polarity':"$o",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source':"$2",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '342 ##':{
    'Name':"$a",
    'Coordinate units or distance units':"$b",
    'Latitude resolution':"$c",
    'Longitude resolution':"$d",
    'Standard parallel or oblique line latitude':"$e",
    'Oblique line longitude':"$f",
    'Longitude of central meridian or projection center':"$g",
    'Latitude of projection center or projection origin':"$h",
    'False easting':"$i",
    'False Northing':"$j",
    'Scale factor':"$k",
    'Height of perspective point above surface':"$l",
    'Azimuthal angle':"$m",
    'Azimuth measure point longitude or straight vertival longitude from pole':"$n",
    'Landsat number and path number':"$o",
    'Zone identifier':"$p",
    'Ellipsoid name':"$q",
    'Semi-major axis':"$r",
    'Denominator of flattening ratio':"$s",
    'Vertical resolution':"$t",
    'Vertical encoding method':"$u",
    'Local planar, local, or other projection or grid description':"$v",
    'Local planar or local georeference information':"$w",
    'Reference method used':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '343 ##':{
    'Planar coordinate encoding method':"$a",
    'Planar distance units':"$b",
    'Abscissa resolution':"$c",
    'Ordinate resolution':"$d",
    'Distance resolution':"$e",
    'Bearing resolution':"$f",
    'Bearing units':"$g",
    'Bearing reference direction':"$h",
    'Bearing reference meridian':"$i",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '344 ##':{
    'Type of recording':"$a",
    'Recording medium':"$b",
    'Playing speed':"$c",
    'Groove characteristic':"$d",
    'Track configuration':"$e",
    'Tape configuration':"$f",
    'Configuration of playback channels':"$g",
    'Special playback characteristics':"$h",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source':"$2",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '345 ##':{
    'Presentation format':"$a",
    'Projection speed':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source':"$2",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '346 ##':{
    'Video format':"$a",
    'Broadcast standard':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source':"$2",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '347 ##':{
    'File type':"$a",
    'Encoding format':"$b",
    'File size':"$c",
    'Resolution':"$d",
    'Regional encoding':"$e",
    'Encoded bitrate':"$f",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source':"$2",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '348 ##':{
    'Format of notated music term':"$a",
    'Format of notated music code':"$b",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of term':"$2",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '351 ##':{
    'Organization':"$a",
    'Arrangement':"$b",
    'Hierarchical level':"$c",
    'Materials specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '352 ##':{
    'Direct reference method':"$a",
    'Object type':"$b",
    'Object count':"$c",
    'Row count':"$d",
    'Column count':"$e",
    'Vertical count':"$f",
    'VPF topology level':"$g",
    'Indirect reference description':"$i",
    'Format of the digital image':"$q",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '355 ##':{
    'Security classification':"$a",
    'Handling instructions':"$b",
    'External dissemination information':"$c",
    'Downgrading or declassification event':"$d",
    'Classification system':"$e",
    'Country of origin code':"$f",
    'Downgrading date':"$g",
    'Declassification date':"$h",
    'Authorization':"$j",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '357 ##':{
    'Originator control term':"$a",
    'Originating agency':"$b",
    'Authorized recipients of material':"$c",
    'Other restrictions':"$g",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '362 ##':{
    'Dates of publication and/or sequential designation':"$a",
    'Source of information':"$z",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '363 ##':{
    'First level of enumeration':"$a",
    'Second level of enumeration':"$b",
    'Third level of enumeration':"$c",
    'Fourth level of enumeration':"$d",
    'Fifth level of enumeration':"$e",
    'Sixth level of enumeration':"$f",
    'Alternative numbering scheme, first level of enumeration':"$g",
    'Alternative numbering scheme, second level of enumeration':"$h",
    'First level of chronology':"$i",
    'Second level of chronology':"$j",
    'Third level of chronology':"$k",
    'Fourth level of chronology':"$l",
    'Alternative numbering scheme, chronology':"$m",
    'First level textual designation':"$u",
    'First level of chronology, issuance':"$v",
    'Nonpublic note':"$x",
    'Public note':"$z",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '365 ##':{
    'Price type code':"$a",
    'Price amount':"$b",
    'Currency code':"$c",
    'Unit of pricing':"$d",
    'Price note':"$e",
    'Price effective from':"$f",
    'Price effective until':"$g",
    'Tax rate 1':"$h",
    'Tax rate 2':"$i",
    'ISO country code':"$j",
    'MARC country code':"$k",
    'Identification of pricing entity':"$m",
    'Source of price type code':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '366 ##':{
    'Publisher\'s compressed title identification':"$a",
    'Detailed date of publication':"$b",
    'Availability status code':"$c",
    'Expected next availability date':"$d",
    'Note':"$e",
    'Publisher\'s discount category':"$f",
    'Date made out of print':"$g",
    'ISO country code':"$j",
    'MARC country code':"$k",
    'Identification of agency':"$m",
    'Source of availability status code':"$2",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '370 ##':{
    'Associated country':"$c",
    'Other associated place':"$f",
    'Place of origin of work or expression':"$g",
    'Relationship information':"$i",
    'Start period':"$s",
    'End period':"$t",
    'Uniform Resource Identifier':"$u",
    'Source of information':"$v",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of term':"$2",
    'Material specified':"$3",
    'Relationship':"$4",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '377 ##':{
    'Language code':"$a",
    'Language term':"$l",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source':"$2",
    'Material specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '380 ##':{
    'Form of work':"$a",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of term':"$2",
    'Material specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '381 ##':{
    'Other distinguishing characteristic':"$a",
    'Uniform Resource Identifier':"$u",
    'Source of information':"$v",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of term':"$2",
    'Material specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '382 ##':{
    'Medium of performance':"$a",
    'Soloist':"$b",
    'Doubling instrument':"$d",
    'Number of ensembles of the same type':"$e",
    'Number of performers of the same medium':"$n",
    'Alternative medium of performance':"$p",
    'Total number of individuals performing alongside ensembles':"$r",
    'Total number of performers':"$s",
    'Total number of ensembles':"$t",
    'Note':"$v",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of term':"$2",
    'Material specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '383 ##':{
    'Serial number':"$a",
    'Opus number':"$b",
    'Thematic index number':"$c",
    'Thematic index code':"$d",
    'Publisher associated with opus number':"$e",
    'Source':"$2",
    'Material specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '384 ##':{
    'Key':"$a",
    'Material specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '385 ##':{
    'Audience term':"$a",
    'Audience code':"$b",
    'Demographic group term':"$m",
    'Demographic group code':"$n",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source':"$2",
    'Material specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '386 ##':{
    'Creator/contributor term':"$a",
    'Creator/contributor code':"$b",
    'Relationship information':"$i",
    'Demographic group term':"$m",
    'Demographic group code':"$n",
    'Alternative medium of performance':"$p",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source':"$2",
    'Material specified':"$3",
    'Relationship':"$4",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '388 ##':{
    'Time period of creation term':"$a",
    'Authority record control number or standard number':"$0",
    'Real World Object URI':"$1",
    'Source of term':"$2",
    'Material specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '490 ##':{
    'Series statement':"$a",
    'Library of Congress call number':"$l",
    'Volume/sequential designation':"$v",
    'International Standard Serial Number':"$x",
    'Material specified':"$3",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '500 ##':{
    'General note':"$a",
    'Material specified':"$3",
    'Institution to which field applies':"$5",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '501 ##':{
    'With note':"$a",
    'Institution to which field applies':"$5",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '502 ##':{
    'Dissertation note':"$a",
    'Degree type':"$b",
    'Name of granting institution':"$c",
    'Year degree granted':"$d",
    'Miscellaneous information':"$g",
    'Dissertation identifier':"$o",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '504 ##':{
    'Bibliography, etc. note':"$a",
    'Number of references':"$b",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    '505 ##':{
    'Formatted contents note':"$a",
    'Miscellaneous information':"$g",
    'Statement of responsibility':"$r",
    'Title':"$t",
    'Uniform Resource Identifier':"$u",
    'Linkage':"$6",
    'Field link and sequence number':"$8",
    },
    }

Indicator={
    '--':"--Please choose a Variable Data Field--"
    ,
    '010 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '013 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '015 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '016 ##':"-----First Indicator-----\nNational bibliographic agency\n# - Library and Archives Canada\n7 - Source specified in subfield $2\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '017 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nDisplay constant controller\n# - Copyright/legal deposit number\n8 - No display constant generated"
    ,
    '018 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '020 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '022 ##':"-----First Indicator-----\nLevel of international interest\n# - No level specified\n0 - Continuing international interest\n1 - No continuing international interest\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '024 ##':"-----First Indicator-----\nType of standard number or code\n0 - International Standard Recording Code\n1 - Universal Product Code\n2 - International Standard Music Number\n3 - International Article Number\n4 - Serial Item/Contribution Identifier\n7 - Source specified in subfield $2\n8 - Unspecified type of standard number/code\n-----Second Indicator-----\nDifference indicator\n# - No information provided\n0 - No difference\n1 - Difference"
    ,
    '025 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '027 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '028 ##':"-----First Indicator-----\nType of number\n0 - Issue number\n1 - Matrix number\n2 - Plate number\n3 - Other music publisher number\n4 - Video recording publisher number\n5 - Other publisher number\n6 - Distributor number\n-----Second Indicator-----\nNote/added entry controller\n0 - No note, no added entry\n1 - Note, added entry\n2 - Note, no added entry\n3 - No note, added entry"
    ,
    '030 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '031 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '032 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '033 ##':"-----First Indicator-----\nType of date in subfield $a\n# - No date information\n0 - Single date\n1 - Multiple single dates\n2 - Range of dates\n-----Second Indicator-----\nType of event\n# - No information provided\n0 - Capture\n1 - Broadcast\n2 - Finding"
    ,
    '034 ##':"-----First Indicator-----\nType of scale\n0 - Scale indeterminable/No scale recorded\n1 - Single scale\n3 - Range of scales\n-----Second Indicator-----\nType of ring\n# - Not applicable\n0 - Outer ring\n1 - Exclusion ring"
    ,
    '035 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '036 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '037 ##':"-----First Indicator-----\nSource of acquisition sequence\n# - Not applicable/No information provided/Earliest\n2 - Intervening\n3 - Current/Latest\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '038 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '040 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '041 ##':"-----First Indicator-----\nTranslation indication\n# - No information provided\n0 - Item not a translation/does not include a translation\n1 - Item is or includes a translation\n-----Second Indicator-----\nSource of code\n# - MARC language code\n7 - Source specified in subfield $2"
    ,
    '042 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '043 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '044 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '045 ##':"-----First Indicator-----\nType of time period in subfield $b or $c\n# - Subfield $b or $c not present\n0 - Single date/time\n1 - Multiple single dates/times\n2 - Range of dates/times\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '046 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '047 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nSource of code\n# - MARC musical composition code\n7 - Source specified in subfield $2"
    ,
    '048 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nSource of code\n# - MARC code\n7 - Source specified in subfield $2"
    ,
    '050 ##':"-----First Indicator-----\nExistence in LC collection\n# - No information provided\n0 - Item is in LC\n1 - Item is not in LC\n-----Second Indicator-----\nSource of call number\n0 - Assigned by LC\n4 - Assigned by agency other than LC"
    ,
    '051 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '052 ##':"-----First Indicator-----\nCode source\n# - Library of Congress Classification\n1 - U.S. Dept. of Defence Classification\n7 - Source specified in subfield $2\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '055 ##':"-----First Indicator-----\nExistence in LAC collection\n# - Information not provided\n0 - Word held by LAC\n1 - Work not held by LAC\n-----Second Indicator-----\nType, completeness, source of class/call number\n0 - LC-based call number assigned by LAC\n1 - Complete LC class number assigned by LAC\n2 - Incomplete LC class number assigned by LAC\n3 - LC-based call number assigned by the contributing library\n4 - Complete LC class number assigned by the contributing library\n5 - Incomplete LC class number assigned by the contributing library\n6 - Other call number assigned by the LAC\n7 - Other class number assigned by LAC\n8 - Other call number assigned by the contributing library\n9 - Other class number assigned by the contributing library"
    ,
    '060 ##':"-----First Indicator-----\nExistence in NLM collection\n# - No information provided\n0 - Item is in NLM\n1 - Item is not in NLM\n-----Second Indicator-----\nSource of call number\n0 - Assigned by NLM\n4 - Assigned by agency other than NLM"
    ,
    '061 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '066 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '070 ##':"-----First Indicator-----\nExistence in NAL collection\n# - No information provided\n0 - Item is in NAL\n1 - Item is not in NAL\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '071 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '072 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nCode source\n0 - NAL subject category code list\n7 - Source specified in subfield $2"
    ,
    '074 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '080 ##':"-----First Indicator-----\nType of edition\n# - No information provided\n0 - Full\n1 - Abridged\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '082 ##':"-----First Indicator-----\nType of edition\n0 - Full edition\n1 - Abridged edition\n7 - Other edition specified in subfield $2\n-----Second Indicator-----\nSource of classification number\n# - No information provided\n0 - Assigned by LC\n4 - Assigned by agency other than LC"
    ,
    '084 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '085 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '086 ##':"-----First Indicator-----\nNumber source\n# - Source speficied in subfield $2\n0 - Superintendent of Documents Classification System\n1 - Government of Canada Publications: Outline of Classification\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '088 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '210 ##':"-----First Indicator-----\nTitle added entry\n0 - No added entry\n1 - Added entry\n-----Second Indicator-----\nType\n# - Abbreviated key title\n0 - Other abbreviated title"
    ,
    '222 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nNonfiling characters\n0 - No nonfiling characters\n1-9 - Number of nonfiling characters"
    ,
    '240 ##':"-----First Indicator-----\nUniform title printed or displayed\n0 - Not printed or displayed\n1 - Printed or displayed\n-----Second Indicator-----\nNonfiling characters\n0-9 - Number of nonfiling characters"
    ,
    '242 ##':"-----First Indicator-----\nTitle added entry\n0 - No added entry\n1 - Added entry\n-----Second Indicator-----\nNonfiling characters\n0 - No nonfiling characters\n1-9 - Number of nonfiling characters"
    ,
    '243 ##':"-----First Indicator-----\nUniform title printed or displayed\n0 - Not printed or displayed\n1 - Printed or displayed\n-----Second Indicator-----\nNonfiling characters\n0-9 - Number of nonfiling characters"
    ,
    '245 ##':"-----First Indicator-----\nTitle added entry\n0 - No added entry\n1 - Added entry\n-----Second Indicator-----\nNonfiling characters\n0 - No nonfiling characters\n1-9 - Number of nonfiling characters"
    ,
    '246 ##':"-----First Indicator-----\nNote/added entry controller\n0 - Note, no added entry\n1 - Note, added entry\n2 - No note, no added entry\n3 - No note, added entry\n-----Second Indicator-----\nType of title\n# - No type specified\n0 - Portion of title\n1 - Parallel title\n2 - Distinctive title\n3 - Other title\n4 - Cover title\n5 - Added title page title\n6 - Caption title\n7 - Running title\n8 - Spine title"
    ,
    '247 ##':"-----First Indicator-----\nTitle added entry\n0 - No added entry\n1 - Added entry\n-----Second Indicator-----\nNote controller\n0 - Display note\n1 - Do not display note"
    ,
    '250 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '254 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '255 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '256 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '257 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '258 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '260 ##':"-----First Indicator-----\nSequence of publishing statements\n# - Not applicable/No information/Earliest available publisher\n2 - Intervening publisher\n3 - Current/latest publisher\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '263 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '264 ##':"-----First Indicator-----\nSequence of statements\n# - Not applicable/No information provided/Earliest\n2 - Intervening\n3 - Current/Latest\n-----Second Indicator-----\nFunction of entity\n0 - Production\n1 - Publication\n2 - Distribution\n3 - Manufacture\n4 - Copyright notice date"
    ,
    '270 ##':"-----First Indicator-----\nLevel\n# - No level specified\n1 - Primary\n2 - Secondary\n-----Second Indicator-----\nType of address\n# - No type specified\n0 - Mailing\n7 - Type specified in subfield $i"
    ,
    '300 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '306 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '307 ##':"-----First Indicator-----\nDisplay constant controller\n# - Hours\n8 - No display constant generated\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '310 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '321 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '336 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '337 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '338 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '340 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '342 ##':"-----First Indicator-----\nGeospatial reference dimension\n0 - Horizontal coordinate system\n1 - Vertical coordinate system\n-----Second Indicator-----\nGeospatial reference method\n0 - Geographic\n1 - Map projection\n2 - Grid coordinate system\n3 - Local planar\n4 - Local\n5 - Geodetic model\n6 - Altitude\n7 - Method specified in $2\n8 - Depth"
    ,
    '343 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '344 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '345 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '346 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '347 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '348 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '351 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '352 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '355 ##':"-----First Indicator-----\nControlled element\n0 - Document\n1 - Title\n2 - Abstract\n3 - Contents note\n4 - Author\n5 - Record\n8 - None of the above\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '357 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '362 ##':"-----First Indicator-----\nFormat of date\n0 - Formatted style\n1 - Unformatted note\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '363 ##':"-----First Indicator-----\nStart/End designator\n# - No information provided\n0 - Starting information\n1 - Ending information\n-----Second Indicator-----\nState of issuance\n# - Not specified\n0 - Closed\n1 - Open"
    ,
    '365 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '366 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '370 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '377 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nSource of code\n# - MARC language code\n7 - Source specified in $2"
    ,
    '380 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '381 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '382 ##':"-----First Indicator-----\nDisplay constant controller\n# - No information provided\n0 - Medium of performance\n1 - Partial medium of performance\n-----Second Indicator-----\nAccess control\n# - No information provided\n0 - Not intended for access\n1 - Intended for access"
    ,
    '383 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '384 ##':"-----First Indicator-----\nKey type\n# - Relationship to original unknown\n0 - Original key\n1 - Transposed key\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '385 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '386 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '388 ##':"-----First Indicator-----\nType of time period\n# - No information provided\n1 - Creation of work\n2 - Creation of aggregate work\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '490 ##':"-----First Indicator-----\nSeries tracing policy\n0 - Series not traced\n1 - Series traced\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '500 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '501 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '502 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '504 ##':"-----First Indicator-----\nUndefined\n# - Undefined\n-----Second Indicator-----\nUndefined\n# - Undefined"
    ,
    '505 ##':"-----First Indicator-----\nDisplay constant controller\n0 - Contents\n1 - Incomplete contents\n2 - Partial contents\n8 - No display constant generated\n-----Second Indicator-----\nLevel of content designation\n# - Basic\n0 - Enhanced"
    ,
    }

